### ISSUE TITLE
Typo in the Translation script

### ISSUE THREAD

**Issue by AhmedIdr** [muellerzr/minimal-trainer-zoo#1]
Hey, thank you so much for the scripts. When I was looking at the translation script, I noticed a typo: `metric= "sacreblue"`. It should be `sacrebleu`. Additionally, I noticed that the dataset split is not specified when loading the dataset, which will probably throw an error, it should be like this `load_dataset(dataset_name, language_set)`. Also `result = metric.compute(predictions=decoded_preds, references=decoded_labels)` should be `result = sacrebleu.compute(predictions=decoded_preds, references=decoded_labels)`. If needed, I can also create a PR with the fixes.

**Comment by muellerzr** [comment]
A PR would be great! Otherwise I’ll get to them tommorow 🤗 

(will be doing some modifications to ensure all scripts can be ran in <5-10 min tops)
